server:
  port: 9009
spring:
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    url: jdbc:mysql://${MYSQL_IP:localhost}:${MYSQL_PORT:3306}/hcms
    username: ${MYSQL_USERNAME:hcms}
    password: ${MYSQL_PASSWORD:ddd-hcms}
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 4
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 10000
  web:
    resources:
      static-locations: classpath:/static/,classpath:/views/
graceful-response:
  print-exception-in-global-advice: true
  response-style: 1

